# Generated by Django 5.1 on 2024-08-24 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
